name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the problem.
      placeholder: Brief summary
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide a minimal reproducible example if possible.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SDK version
      placeholder: e.g. 1.0.0-SNAPSHOT
  - type: input
    id: java
    attributes:
      label: Java version
      placeholder: e.g. 21.0.4
  - type: textarea
    id: logs
    attributes:
      label: Logs/stack traces
      description: Please paste relevant logs. Use code fences if needed.
      render: shell
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I can reproduce this with the latest main branch
          required: false
