name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement or new feature!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of the feature.
      placeholder: Brief summary
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
